import { brand, grey, status } from "./global.ts"

/**
 * Alias (semantic) colour tokens, named by role. Components use only these.
 * Each theme must define every key (enforced by the ColorTheme type).
 */
export const colorTokenNames = [
  "colorNeutralForeground1",
  "colorNeutralForeground2",
  "colorNeutralForeground3",
  "colorNeutralForegroundDisabled",
  "colorNeutralForegroundOnBrand",
  "colorNeutralBackground1",
  "colorNeutralBackground1Hover",
  "colorNeutralBackground1Pressed",
  "colorNeutralBackground2",
  "colorNeutralBackground3",
  "colorNeutralBackgroundDisabled",
  "colorSubtleBackgroundHover",
  "colorSubtleBackgroundPressed",
  "colorNeutralStroke1",
  "colorNeutralStroke1Hover",
  "colorNeutralStroke2",
  "colorNeutralStrokeAccessible",
  "colorNeutralStrokeDisabled",
  "colorBrandBackground",
  "colorBrandBackgroundHover",
  "colorBrandBackgroundPressed",
  "colorBrandBackground2",
  "colorBrandForeground1",
  "colorBrandForeground2",
  "colorBrandStroke1",
  "colorStrokeFocus1",
  "colorStrokeFocus2",
  "colorStatusDangerForeground1",
  "colorStatusDangerBackground1",
  "colorStatusDangerBorder1",
  "colorStatusWarningForeground1",
  "colorStatusWarningBackground1",
  "colorStatusWarningBorder1",
  "colorStatusSuccessForeground1",
  "colorStatusSuccessBackground1",
  "colorStatusSuccessBorder1",
  "colorStatusInfoForeground1",
  "colorStatusInfoBackground1",
  "colorStatusInfoBorder1",
  "colorBackgroundOverlay",
  "colorNeutralBackgroundStrong",
  "colorStatusDangerBackground3",
  "colorStatusWarningBackground3",
  "colorStatusSuccessBackground3",
  "colorStatusInfoBackground3",
] as const

export type ColorTokenName = (typeof colorTokenNames)[number]
export type ColorTheme = Record<ColorTokenName, string>

export const lightColors: ColorTheme = {
  colorNeutralForeground1: grey(14),
  colorNeutralForeground2: grey(26),
  colorNeutralForeground3: grey(38),
  colorNeutralForegroundDisabled: grey(74),
  colorNeutralForegroundOnBrand: "#ffffff",
  colorNeutralBackground1: "#ffffff",
  colorNeutralBackground1Hover: grey(96),
  colorNeutralBackground1Pressed: grey(88),
  colorNeutralBackground2: grey(98),
  colorNeutralBackground3: grey(96),
  colorNeutralBackgroundDisabled: grey(94),
  colorSubtleBackgroundHover: grey(96),
  colorSubtleBackgroundPressed: grey(88),
  colorNeutralStroke1: grey(82),
  colorNeutralStroke1Hover: grey(78),
  colorNeutralStroke2: grey(88),
  colorNeutralStrokeAccessible: grey(38),
  colorNeutralStrokeDisabled: grey(88),
  colorBrandBackground: brand[80],
  colorBrandBackgroundHover: brand[70],
  colorBrandBackgroundPressed: brand[40],
  colorBrandBackground2: brand[160],
  colorBrandForeground1: brand[80],
  colorBrandForeground2: brand[70],
  colorBrandStroke1: brand[80],
  colorStrokeFocus1: "#ffffff",
  colorStrokeFocus2: "#000000",
  colorStatusDangerForeground1: status.danger.shade,
  colorStatusDangerBackground1: status.danger.tint,
  colorStatusDangerBorder1: status.danger.primary,
  colorStatusWarningForeground1: status.warning.shade,
  colorStatusWarningBackground1: status.warning.tint,
  colorStatusWarningBorder1: status.warning.primary,
  colorStatusSuccessForeground1: status.success.shade,
  colorStatusSuccessBackground1: status.success.tint,
  colorStatusSuccessBorder1: status.success.primary,
  colorStatusInfoForeground1: status.info.shade,
  colorStatusInfoBackground1: status.info.tint,
  colorStatusInfoBorder1: status.info.primary,
  colorBackgroundOverlay: "rgba(0, 0, 0, 0.4)",
  colorNeutralBackgroundStrong: grey(38),
  colorStatusDangerBackground3: status.danger.primary,
  colorStatusWarningBackground3: status.warning.shade,
  colorStatusSuccessBackground3: status.success.primary,
  colorStatusInfoBackground3: status.info.primary,
}

export const darkColors: ColorTheme = {
  colorNeutralForeground1: "#ffffff",
  colorNeutralForeground2: grey(84),
  colorNeutralForeground3: grey(68),
  colorNeutralForegroundDisabled: grey(36),
  colorNeutralForegroundOnBrand: "#ffffff",
  colorNeutralBackground1: grey(16),
  colorNeutralBackground1Hover: grey(24),
  colorNeutralBackground1Pressed: grey(12),
  colorNeutralBackground2: grey(12),
  colorNeutralBackground3: grey(8),
  colorNeutralBackgroundDisabled: grey(8),
  colorSubtleBackgroundHover: grey(22),
  colorSubtleBackgroundPressed: grey(18),
  colorNeutralStroke1: grey(40),
  colorNeutralStroke1Hover: grey(46),
  colorNeutralStroke2: grey(32),
  colorNeutralStrokeAccessible: grey(68),
  colorNeutralStrokeDisabled: grey(26),
  colorBrandBackground: brand[70],
  colorBrandBackgroundHover: brand[80],
  colorBrandBackgroundPressed: brand[40],
  colorBrandBackground2: brand[20],
  colorBrandForeground1: brand[110],
  colorBrandForeground2: brand[120],
  colorBrandStroke1: brand[100],
  colorStrokeFocus1: "#000000",
  colorStrokeFocus2: "#ffffff",
  colorStatusDangerForeground1: status.danger.darkFg,
  colorStatusDangerBackground1: status.danger.darkTint,
  colorStatusDangerBorder1: status.danger.primary,
  colorStatusWarningForeground1: status.warning.darkFg,
  colorStatusWarningBackground1: status.warning.darkTint,
  colorStatusWarningBorder1: status.warning.primary,
  colorStatusSuccessForeground1: status.success.darkFg,
  colorStatusSuccessBackground1: status.success.darkTint,
  colorStatusSuccessBorder1: status.success.primary,
  colorStatusInfoForeground1: status.info.darkFg,
  colorStatusInfoBackground1: status.info.darkTint,
  colorStatusInfoBorder1: status.info.primary,
  colorBackgroundOverlay: "rgba(0, 0, 0, 0.6)",
  colorNeutralBackgroundStrong: grey(38),
  colorStatusDangerBackground3: status.danger.primary,
  colorStatusWarningBackground3: status.warning.shade,
  colorStatusSuccessBackground3: status.success.primary,
  colorStatusInfoBackground3: status.info.primary,
}

/** High contrast maps roles to CSS system colours (forced-colors friendly). */
export const highContrastColors: ColorTheme = {
  colorNeutralForeground1: "CanvasText",
  colorNeutralForeground2: "CanvasText",
  colorNeutralForeground3: "CanvasText",
  colorNeutralForegroundDisabled: "GrayText",
  colorNeutralForegroundOnBrand: "HighlightText",
  colorNeutralBackground1: "Canvas",
  colorNeutralBackground1Hover: "Canvas",
  colorNeutralBackground1Pressed: "Canvas",
  colorNeutralBackground2: "Canvas",
  colorNeutralBackground3: "Canvas",
  colorNeutralBackgroundDisabled: "Canvas",
  colorSubtleBackgroundHover: "Canvas",
  colorSubtleBackgroundPressed: "Canvas",
  colorNeutralStroke1: "CanvasText",
  colorNeutralStroke1Hover: "Highlight",
  colorNeutralStroke2: "CanvasText",
  colorNeutralStrokeAccessible: "CanvasText",
  colorNeutralStrokeDisabled: "GrayText",
  colorBrandBackground: "Highlight",
  colorBrandBackgroundHover: "Highlight",
  colorBrandBackgroundPressed: "Highlight",
  colorBrandBackground2: "Canvas",
  colorBrandForeground1: "LinkText",
  colorBrandForeground2: "LinkText",
  colorBrandStroke1: "Highlight",
  colorStrokeFocus1: "Canvas",
  colorStrokeFocus2: "Highlight",
  colorStatusDangerForeground1: "CanvasText",
  colorStatusDangerBackground1: "Canvas",
  colorStatusDangerBorder1: "CanvasText",
  colorStatusWarningForeground1: "CanvasText",
  colorStatusWarningBackground1: "Canvas",
  colorStatusWarningBorder1: "CanvasText",
  colorStatusSuccessForeground1: "CanvasText",
  colorStatusSuccessBackground1: "Canvas",
  colorStatusSuccessBorder1: "CanvasText",
  colorStatusInfoForeground1: "CanvasText",
  colorStatusInfoBackground1: "Canvas",
  colorStatusInfoBorder1: "CanvasText",
  colorBackgroundOverlay: "rgba(0, 0, 0, 0.6)",
  colorNeutralBackgroundStrong: "Highlight",
  colorStatusDangerBackground3: "Highlight",
  colorStatusWarningBackground3: "Highlight",
  colorStatusSuccessBackground3: "Highlight",
  colorStatusInfoBackground3: "Highlight",
}
