import {
  type ColorTheme,
  darkColors,
  highContrastColors,
  lightColors,
} from "./alias.ts"
import {
  darkShadows,
  foundations,
  lightShadows,
  motion,
} from "./foundations.ts"

function block(selector: string, vars: Record<string, string>, extra = "") {
  const lines = Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`)
  return `${selector} {\n${extra}${lines.join("\n")}\n}`
}

function theme(
  colors: ColorTheme,
  shadows: Record<string, string>,
  scheme: string
) {
  return {
    vars: { ...colors, ...shadows },
    extra: `  color-scheme: ${scheme};\n`,
  }
}

/** Renders every token as CSS custom properties (see scripts/build-tokens.ts). */
export function renderTokensCss(): string {
  const light = theme(lightColors, lightShadows, "light")
  const dark = theme(darkColors, darkShadows, "dark")
  const hc = theme(highContrastColors, lightShadows, "light dark")
  const reducedMotion = Object.fromEntries(
    Object.keys(motion)
      .filter((k) => k.startsWith("duration"))
      .map((k) => [k, "0ms"])
  )
  return [
    "/* GENERATED by packages/ui-kit/scripts/build-tokens.ts — do not edit. */",
    block(":root", foundations),
    block(
      ':root:not([data-theme]),\n:root[data-theme="light"]',
      light.vars,
      light.extra
    ),
    `@media (prefers-color-scheme: dark) {\n${indent(block(":root:not([data-theme])", dark.vars, dark.extra))}\n}`,
    block(':root[data-theme="dark"]', dark.vars, dark.extra),
    block(':root[data-theme="hc"]', hc.vars, hc.extra),
    `@media (prefers-reduced-motion: reduce) {\n${indent(block(":root", reducedMotion))}\n}`,
    "",
  ].join("\n\n")
}

function indent(text: string) {
  return text
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n")
}
