#!/usr/bin/env node
// Generates packages/api-client/src/generated.ts from api/openapi.yaml:
// one TS type + one strict runtime decoder per components.schemas entry
// (ADR-0018). Supports a deliberately small subset of JSON Schema and fails
// loudly on anything else.
//
// Usage: node scripts/gen-api.mjs [--check]
import { execFileSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { parse } from "yaml"

const root = path.resolve(import.meta.dirname, "..")
const specPath = path.join(root, "api/openapi.yaml")
const outPath = path.join(root, "packages/api-client/src/generated.ts")
const spec = parse(fs.readFileSync(specPath, "utf8"))
const schemas = spec.components?.schemas ?? {}

const SUPPORTED = new Set([
  "type",
  "properties",
  "required",
  "items",
  "enum",
  "$ref",
  "anyOf",
  "additionalProperties",
  "format",
  "description",
  "example",
  "minLength",
  "maxLength",
])

function check(schema, where) {
  for (const key of Object.keys(schema)) {
    if (!SUPPORTED.has(key))
      throw new Error(`${where}: unsupported keyword "${key}"`)
  }
}

const refName = (ref) => {
  const m = /^#\/components\/schemas\/(\w+)$/.exec(ref)
  if (!m) throw new Error(`unsupported $ref ${ref}`)
  return m[1]
}

const typesOf = (s) => (Array.isArray(s.type) ? s.type : s.type ? [s.type] : [])

function tsType(s, where) {
  check(s, where)
  if (s.$ref) return refName(s.$ref)
  if (s.anyOf)
    return s.anyOf.map((x, i) => tsType(x, `${where}.anyOf[${i}]`)).join(" | ")
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ")
  const types = typesOf(s)
  if (types.length > 1) {
    return types.map((t) => tsType({ ...s, type: t }, where)).join(" | ")
  }
  switch (types[0]) {
    case "null":
      return "null"
    case "string":
      return "string"
    case "integer":
    case "number":
      return "number"
    case "boolean":
      return "boolean"
    case "array": {
      const item = tsType(s.items ?? {}, `${where}.items`)
      return item.includes("|") ? `(${item})[]` : `${item}[]`
    }
    case "object": {
      if (s.additionalProperties && !s.properties) {
        return `Record<string, ${tsType(s.additionalProperties, `${where}.additionalProperties`)}>`
      }
      const req = new Set(s.required ?? [])
      const fields = Object.entries(s.properties ?? {}).map(
        ([k, v]) =>
          `${k}${req.has(k) ? "" : "?"}: ${tsType(v, `${where}.${k}`)}`
      )
      return `{ ${fields.join("; ")} }`
    }
    default:
      throw new Error(
        `${where}: missing or unsupported type ${JSON.stringify(s.type)}`
      )
  }
}

/** Returns a TS expression decoding `v` (an expression) at JSON path `p`. */
function decodeExpr(s, v, p, where) {
  if (s.$ref) return `decode${refName(s.$ref)}(${v}, ${p})`
  const nullable =
    (s.anyOf ?? []).some((x) => typesOf(x).includes("null")) ||
    (typesOf(s).includes("null") && typesOf(s).length > 1)
  if (nullable) {
    const rest = s.anyOf
      ? s.anyOf.filter((x) => !typesOf(x).includes("null"))
      : [{ ...s, type: typesOf(s).filter((t) => t !== "null")[0] }]
    if (rest.length !== 1)
      throw new Error(`${where}: only "X | null" unions are supported`)
    return `${v} === null ? null : ${decodeExpr(rest[0], v, p, where)}`
  }
  if (s.anyOf) throw new Error(`${where}: only "X | null" unions are supported`)
  if (s.enum) return `decEnum(${v}, ${p}, ${JSON.stringify(s.enum)} as const)`
  switch (typesOf(s)[0]) {
    case "string":
      return `decString(${v}, ${p})`
    case "integer":
      return `decNumber(${v}, ${p}, true)`
    case "number":
      return `decNumber(${v}, ${p}, false)`
    case "boolean":
      return `decBoolean(${v}, ${p})`
    case "array":
      return `decArray(${v}, ${p}, (x, xp) => ${decodeExpr(s.items, "x", "xp", `${where}.items`)})`
    case "object": {
      if (s.additionalProperties && !s.properties) {
        return `decRecord(${v}, ${p}, (x, xp) => ${decodeExpr(s.additionalProperties, "x", "xp", where)})`
      }
      const req = new Set(s.required ?? [])
      const fields = Object.entries(s.properties ?? {}).map(([k, sub]) => {
        const expr = decodeExpr(
          sub,
          `o.${k}`,
          `\`\${${p}}.${k}\``,
          `${where}.${k}`
        )
        return req.has(k)
          ? `${k}: ${expr}`
          : `...(o.${k} === undefined ? {} : { ${k}: ${expr} })`
      })
      return `decObject(${v}, ${p}, (o) => ({ ${fields.join(", ")} }))`
    }
    default:
      throw new Error(`${where}: cannot decode type ${JSON.stringify(s.type)}`)
  }
}

const header = `/* GENERATED by scripts/gen-api.mjs from api/openapi.yaml - do not edit. */
/* Regenerate with \`pnpm gen:api\` (ADR-0018). */

/** A response did not match api/openapi.yaml. \`path\` is a JSON path like $.user.id */
export class DecodeError extends Error {
  constructor(
    readonly path: string,
    readonly expected: string
  ) {
    super(\`Unexpected API response at \${path}: expected \${expected}\`)
    this.name = "DecodeError"
  }
}

type Obj = Record<string, unknown>

function fail(path: string, expected: string): never {
  throw new DecodeError(path, expected)
}
`

// Helpers emitted only when referenced (unused ones would fail noUnusedLocals).
const HELPERS = {
  decObject: `function decObject<T>(v: unknown, p: string, f: (o: Obj) => T): T {
  if (typeof v !== "object" || v === null || Array.isArray(v)) fail(p, "object")
  return f(v as Obj)
}`,
  decRecord: `function decRecord<T>(v: unknown, p: string, f: (x: unknown, p: string) => T): Record<string, T> {
  return decObject(v, p, (o) =>
    Object.fromEntries(Object.entries(o).map(([k, x]) => [k, f(x, \`\${p}.\${k}\`)]))
  )
}`,
  decArray: `function decArray<T>(v: unknown, p: string, f: (x: unknown, p: string) => T): T[] {
  if (!Array.isArray(v)) fail(p, "array")
  return v.map((x, i) => f(x, \`\${p}[\${i}]\`))
}`,
  decString: `function decString(v: unknown, p: string): string {
  return typeof v === "string" ? v : fail(p, "string")
}`,
  decNumber: `function decNumber(v: unknown, p: string, integer: boolean): number {
  if (typeof v !== "number" || Number.isNaN(v)) fail(p, "number")
  if (integer && !Number.isInteger(v)) fail(p, "integer")
  return v
}`,
  decBoolean: `function decBoolean(v: unknown, p: string): boolean {
  return typeof v === "boolean" ? v : fail(p, "boolean")
}`,
  decEnum: `function decEnum<const T extends readonly string[]>(v: unknown, p: string, values: T): T[number] {
  return typeof v === "string" && values.includes(v) ? (v as T[number]) : fail(p, values.join(" | "))
}`,
}

let body = ""
for (const [name, schema] of Object.entries(schemas).sort(([a], [b]) =>
  a.localeCompare(b)
)) {
  const where = `components.schemas.${name}`
  const type = tsType(schema, where)
  const doc = schema.description
    ? `/** ${schema.description.trim().replace(/\n/g, " ")} */\n`
    : ""
  body +=
    typesOf(schema)[0] === "object" && schema.properties
      ? `\n${doc}export interface ${name} ${type}\n`
      : `\n${doc}export type ${name} = ${type}\n`
  body += `export function decode${name}(v: unknown, p = "$"): ${name} {\n  return ${decodeExpr(schema, "v", "p", where)}\n}\n`
}

const used = Object.entries(HELPERS)
  .filter(
    ([name]) =>
      new RegExp(`\\b${name}\\(`).test(body) ||
      (name === "decObject" && body.includes("decRecord("))
  )
  .map(([, src]) => src)
const raw = `${header}\n${used.join("\n")}\n${body}`
const biome = path.join(root, "node_modules/.bin/biome")
const formatted = execFileSync(
  biome,
  ["format", `--stdin-file-path=${outPath}`],
  {
    input: raw,
    encoding: "utf8",
  }
)

const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : ""
if (process.argv.includes("--check")) {
  if (current !== formatted) {
    console.error(
      "packages/api-client/src/generated.ts is stale. Run: pnpm gen:api"
    )
    process.exit(1)
  }
  console.log("API types are up to date.")
} else if (current !== formatted) {
  fs.writeFileSync(outPath, formatted)
  console.log(
    `Wrote ${path.relative(root, outPath)} (${Object.keys(schemas).length} schemas)`
  )
}
