#!/usr/bin/env node
// Generates tool-specific agent adapters from the tool-neutral `.agents/` source.
//
//   .agents/rules/*.md        canonical rules (frontmatter: description, optional paths[])
//   .agents/skills/<name>/    canonical skills (SKILL.md, agentskills format)
//
// Outputs (never edit by hand):
//   .claude/rules  -> symlink to ../.agents/rules   (Claude Code reads `paths` natively)
//   .claude/skills -> symlink to ../.agents/skills
//   .cursor/skills -> symlink to ../.agents/skills
//   .cursor/rules/*.mdc                             (generated: description, globs, alwaysApply)
//   AGENTS.md rule index between the AGENT-RULES markers (for tools without scoped rules)
//
// Usage: node scripts/sync-agents.mjs [--check]
//   --check  exit 1 if any output is missing or stale (for CI and pre-commit).
// No dependencies on purpose (ADR-0012).

import fs from "node:fs"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "..")
const check = process.argv.includes("--check")
const rulesDir = path.join(root, ".agents/rules")
const problems = []

function parseRule(file) {
  const text = fs.readFileSync(file, "utf8")
  const match = text.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) throw new Error(`${file}: missing frontmatter`)
  const meta = { description: "", paths: [] }
  let inPaths = false
  for (const line of match[1].split("\n")) {
    const item = line.match(/^\s+-\s+"?([^"]+)"?\s*$/)
    if (inPaths && item) {
      meta.paths.push(item[1])
      continue
    }
    inPaths = false
    const kv = line.match(/^(\w+):\s*(.*)$/)
    if (!kv) continue
    if (kv[1] === "description") meta.description = kv[2].trim()
    if (kv[1] === "paths") inPaths = true
  }
  if (!meta.description) throw new Error(`${file}: description is required`)
  return { ...meta, body: text.slice(match[0].length) }
}

function writeIfChanged(file, content) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null
  if (current === content) return
  if (check) return problems.push(`stale: ${path.relative(root, file)}`)
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
}

function ensureSymlink(link, target) {
  const abs = path.join(root, link)
  let current = null
  try {
    current = fs.readlinkSync(abs)
  } catch {}
  if (current === target) return
  if (check) return problems.push(`symlink: ${link} -> ${target}`)
  fs.mkdirSync(path.dirname(abs), { recursive: true })
  fs.rmSync(abs, { recursive: true, force: true })
  fs.symlinkSync(target, abs, "dir")
}

const rules = fs
  .readdirSync(rulesDir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => ({ name: f.slice(0, -3), ...parseRule(path.join(rulesDir, f)) }))

// Claude Code: reads `.agents/rules` format as-is through the symlink.
ensureSymlink(".claude/rules", "../.agents/rules")
// Skills: same SKILL.md format for every tool.
ensureSymlink(".claude/skills", "../.agents/skills")
ensureSymlink(".cursor/skills", "../.agents/skills")

// Cursor: .mdc with its own frontmatter keys.
const cursorDir = path.join(root, ".cursor/rules")
const expected = new Set()
for (const rule of rules) {
  const always = rule.paths.length === 0
  const fm = [
    "---",
    `description: ${rule.description}`,
    ...(always ? [] : [`globs: ${rule.paths.join(",")}`]),
    `alwaysApply: ${always}`,
    "---",
    `<!-- GENERATED from .agents/rules/${rule.name}.md by scripts/sync-agents.mjs. Do not edit. -->`,
    "",
  ].join("\n")
  const file = path.join(cursorDir, `${rule.name}.mdc`)
  expected.add(file)
  writeIfChanged(file, fm + rule.body)
}
if (fs.existsSync(cursorDir)) {
  for (const f of fs.readdirSync(cursorDir)) {
    const file = path.join(cursorDir, f)
    if (expected.has(file)) continue
    if (check) problems.push(`orphan: ${path.relative(root, file)}`)
    else fs.rmSync(file)
  }
}

// AGENTS.md index: lets any agent (Codex, Copilot, …) find scoped rules.
const agentsFile = path.join(root, "AGENTS.md")
const agents = fs.readFileSync(agentsFile, "utf8")
const start =
  "<!-- AGENT-RULES:START (generated by scripts/sync-agents.mjs) -->"
const end = "<!-- AGENT-RULES:END -->"
const rows = rules.map((r) => {
  const scope = r.paths.length
    ? r.paths.map((p) => `\`${p}\``).join(", ")
    : "always"
  return `| [\`${r.name}\`](.agents/rules/${r.name}.md) | ${scope} | ${r.description} |`
})
const index = [
  start,
  "| Rule | Applies to | Summary |",
  "|---|---|---|",
  ...rows,
  end,
].join("\n")
const re = new RegExp(
  `${start.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${end}`
)
if (!re.test(agents))
  throw new Error("AGENTS.md is missing the AGENT-RULES markers")
writeIfChanged(agentsFile, agents.replace(re, index))

if (problems.length) {
  console.error(
    "Agent adapters are out of date. Run: node scripts/sync-agents.mjs"
  )
  for (const p of problems) console.error(`  ${p}`)
  process.exit(1)
}
console.log(
  check ? "Agent adapters are up to date." : `Synced ${rules.length} rules.`
)
