/* GENERATED by scripts/gen-api.mjs from api/openapi.yaml - do not edit. */
/* Regenerate with `pnpm gen:api` (ADR-0018). */

/** A response did not match api/openapi.yaml. `path` is a JSON path like $.user.id */
export class DecodeError extends Error {
  constructor(
    readonly path: string,
    readonly expected: string
  ) {
    super(`Unexpected API response at ${path}: expected ${expected}`)
    this.name = "DecodeError"
  }
}

type Obj = Record<string, unknown>

function fail(path: string, expected: string): never {
  throw new DecodeError(path, expected)
}

function decObject<T>(v: unknown, p: string, f: (o: Obj) => T): T {
  if (typeof v !== "object" || v === null || Array.isArray(v)) fail(p, "object")
  return f(v as Obj)
}
function decRecord<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): Record<string, T> {
  return decObject(v, p, (o) =>
    Object.fromEntries(
      Object.entries(o).map(([k, x]) => [k, f(x, `${p}.${k}`)])
    )
  )
}
function decArray<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): T[] {
  if (!Array.isArray(v)) fail(p, "array")
  return v.map((x, i) => f(x, `${p}[${i}]`))
}
function decString(v: unknown, p: string): string {
  return typeof v === "string" ? v : fail(p, "string")
}
function decNumber(v: unknown, p: string, integer: boolean): number {
  if (typeof v !== "number" || Number.isNaN(v)) fail(p, "number")
  if (integer && !Number.isInteger(v)) fail(p, "integer")
  return v
}
function decBoolean(v: unknown, p: string): boolean {
  return typeof v === "boolean" ? v : fail(p, "boolean")
}
function decEnum<const T extends readonly string[]>(
  v: unknown,
  p: string,
  values: T
): T[number] {
  return typeof v === "string" && values.includes(v)
    ? (v as T[number])
    : fail(p, values.join(" | "))
}

export interface ActiveWorkspace {
  id: string
  name: string
  role: Role
  inviteCode: string
}
export function decodeActiveWorkspace(v: unknown, p = "$"): ActiveWorkspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface Attachment {
  id: string
  filename: string
  mimeType: string
  size: number
  uploadedBy: PersonRef | null
  createdAt: string
  downloadUrl: string
}
export function decodeAttachment(v: unknown, p = "$"): Attachment {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    filename: decString(o.filename, `${p}.filename`),
    mimeType: decString(o.mimeType, `${p}.mimeType`),
    size: decNumber(o.size, `${p}.size`, true),
    uploadedBy:
      o.uploadedBy === null
        ? null
        : decodePersonRef(o.uploadedBy, `${p}.uploadedBy`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
    downloadUrl: decString(o.downloadUrl, `${p}.downloadUrl`),
  }))
}

export interface AttachmentResponse {
  attachment: Attachment
}
export function decodeAttachmentResponse(
  v: unknown,
  p = "$"
): AttachmentResponse {
  return decObject(v, p, (o) => ({
    attachment: decodeAttachment(o.attachment, `${p}.attachment`),
  }))
}

export interface AttachmentUploadResponse {
  attachment: Attachment
  upload: UploadTarget
}
export function decodeAttachmentUploadResponse(
  v: unknown,
  p = "$"
): AttachmentUploadResponse {
  return decObject(v, p, (o) => ({
    attachment: decodeAttachment(o.attachment, `${p}.attachment`),
    upload: decodeUploadTarget(o.upload, `${p}.upload`),
  }))
}

export interface ChangeRequest {
  id: string
  kind: ChangeRequestKind
  status: ChangeRequestStatus
  payload: ChangeRequestPayload
  summary: string
  note: string | null
  reviewNote: string | null
  requester: PersonRef | null
  reviewer: PersonRef | null
  createdAt: string
  decidedAt: string | null
}
export function decodeChangeRequest(v: unknown, p = "$"): ChangeRequest {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    kind: decodeChangeRequestKind(o.kind, `${p}.kind`),
    status: decodeChangeRequestStatus(o.status, `${p}.status`),
    payload: decodeChangeRequestPayload(o.payload, `${p}.payload`),
    summary: decString(o.summary, `${p}.summary`),
    note: o.note === null ? null : decString(o.note, `${p}.note`),
    reviewNote:
      o.reviewNote === null ? null : decString(o.reviewNote, `${p}.reviewNote`),
    requester:
      o.requester === null
        ? null
        : decodePersonRef(o.requester, `${p}.requester`),
    reviewer:
      o.reviewer === null ? null : decodePersonRef(o.reviewer, `${p}.reviewer`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
    decidedAt:
      o.decidedAt === null ? null : decString(o.decidedAt, `${p}.decidedAt`),
  }))
}

export type ChangeRequestKind =
  | "UPDATE"
  | "ASSIGNEE_ADD"
  | "ASSIGNEE_REMOVE"
  | "SUBTASK_ADD"
  | "CHECKLIST_ADD"
  | "CHECKLIST_UPDATE"
  | "CHECKLIST_REMOVE"
  | "ATTACHMENT_REMOVE"
export function decodeChangeRequestKind(
  v: unknown,
  p = "$"
): ChangeRequestKind {
  return decEnum(v, p, [
    "UPDATE",
    "ASSIGNEE_ADD",
    "ASSIGNEE_REMOVE",
    "SUBTASK_ADD",
    "CHECKLIST_ADD",
    "CHECKLIST_UPDATE",
    "CHECKLIST_REMOVE",
    "ATTACHMENT_REMOVE",
  ] as const)
}

/** Flat payload; members by kind — UPDATE: field (status|startDate|endDate|dueDate), value ("" clears dueDate), from (server-set); ASSIGNEE_*: userId; SUBTASK_ADD / CHECKLIST_ADD: title; CHECKLIST_UPDATE: itemId + title and/or done; CHECKLIST_REMOVE: itemId; ATTACHMENT_REMOVE: attachmentId. */
export interface ChangeRequestPayload {
  field?: string
  value?: string
  from?: string
  userId?: string
  title?: string
  itemId?: string
  done?: boolean
  attachmentId?: string
}
export function decodeChangeRequestPayload(
  v: unknown,
  p = "$"
): ChangeRequestPayload {
  return decObject(v, p, (o) => ({
    ...(o.field === undefined
      ? {}
      : { field: decString(o.field, `${p}.field`) }),
    ...(o.value === undefined
      ? {}
      : { value: decString(o.value, `${p}.value`) }),
    ...(o.from === undefined ? {} : { from: decString(o.from, `${p}.from`) }),
    ...(o.userId === undefined
      ? {}
      : { userId: decString(o.userId, `${p}.userId`) }),
    ...(o.title === undefined
      ? {}
      : { title: decString(o.title, `${p}.title`) }),
    ...(o.itemId === undefined
      ? {}
      : { itemId: decString(o.itemId, `${p}.itemId`) }),
    ...(o.done === undefined ? {} : { done: decBoolean(o.done, `${p}.done`) }),
    ...(o.attachmentId === undefined
      ? {}
      : { attachmentId: decString(o.attachmentId, `${p}.attachmentId`) }),
  }))
}

export type ChangeRequestStatus =
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "CANCELED"
export function decodeChangeRequestStatus(
  v: unknown,
  p = "$"
): ChangeRequestStatus {
  return decEnum(v, p, ["PENDING", "APPROVED", "REJECTED", "CANCELED"] as const)
}

export interface ChecklistItem {
  id: string
  title: string
  done: boolean
  assignee: PersonRef | null
}
export function decodeChecklistItem(v: unknown, p = "$"): ChecklistItem {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    done: decBoolean(o.done, `${p}.done`),
    assignee:
      o.assignee === null ? null : decodePersonRef(o.assignee, `${p}.assignee`),
  }))
}

export interface ChecklistItemResponse {
  item: ChecklistItem
}
export function decodeChecklistItemResponse(
  v: unknown,
  p = "$"
): ChecklistItemResponse {
  return decObject(v, p, (o) => ({
    item: decodeChecklistItem(o.item, `${p}.item`),
  }))
}

export interface Client {
  id: string
  name: string
  email: string | null
  phone: string | null
  color: LabelColor
  notes: string | null
  taskCount: number
}
export function decodeClient(v: unknown, p = "$"): Client {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: o.email === null ? null : decString(o.email, `${p}.email`),
    phone: o.phone === null ? null : decString(o.phone, `${p}.phone`),
    color: decodeLabelColor(o.color, `${p}.color`),
    notes: o.notes === null ? null : decString(o.notes, `${p}.notes`),
    taskCount: decNumber(o.taskCount, `${p}.taskCount`, true),
  }))
}

export interface ClientInput {
  name: string
  email?: string | null
  phone?: string | null
  color: LabelColor
  notes?: string | null
}
export function decodeClientInput(v: unknown, p = "$"): ClientInput {
  return decObject(v, p, (o) => ({
    name: decString(o.name, `${p}.name`),
    ...(o.email === undefined
      ? {}
      : { email: o.email === null ? null : decString(o.email, `${p}.email`) }),
    ...(o.phone === undefined
      ? {}
      : { phone: o.phone === null ? null : decString(o.phone, `${p}.phone`) }),
    color: decodeLabelColor(o.color, `${p}.color`),
    ...(o.notes === undefined
      ? {}
      : { notes: o.notes === null ? null : decString(o.notes, `${p}.notes`) }),
  }))
}

export interface ClientList {
  clients: Client[]
}
export function decodeClientList(v: unknown, p = "$"): ClientList {
  return decObject(v, p, (o) => ({
    clients: decArray(o.clients, `${p}.clients`, (x, xp) =>
      decodeClient(x, xp)
    ),
  }))
}

export interface ClientRef {
  id: string
  name: string
  color: LabelColor
}
export function decodeClientRef(v: unknown, p = "$"): ClientRef {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    color: decodeLabelColor(o.color, `${p}.color`),
  }))
}

export interface ClientResponse {
  client: Client
}
export function decodeClientResponse(v: unknown, p = "$"): ClientResponse {
  return decObject(v, p, (o) => ({
    client: decodeClient(o.client, `${p}.client`),
  }))
}

export interface Comment {
  id: string
  body: string
  author: PersonRef | null
  mentions: PersonRef[]
  createdAt: string
}
export function decodeComment(v: unknown, p = "$"): Comment {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    body: decString(o.body, `${p}.body`),
    author: o.author === null ? null : decodePersonRef(o.author, `${p}.author`),
    mentions: decArray(o.mentions, `${p}.mentions`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
  }))
}

export interface CommentResponse {
  comment: Comment
}
export function decodeCommentResponse(v: unknown, p = "$"): CommentResponse {
  return decObject(v, p, (o) => ({
    comment: decodeComment(o.comment, `${p}.comment`),
  }))
}

export interface CreateAttachmentRequest {
  filename: string
  mimeType: string
  size: number
}
export function decodeCreateAttachmentRequest(
  v: unknown,
  p = "$"
): CreateAttachmentRequest {
  return decObject(v, p, (o) => ({
    filename: decString(o.filename, `${p}.filename`),
    mimeType: decString(o.mimeType, `${p}.mimeType`),
    size: decNumber(o.size, `${p}.size`, true),
  }))
}

export interface CreateChangeRequest {
  kind: ChangeRequestKind
  payload: ChangeRequestPayload
  note?: string | null
}
export function decodeCreateChangeRequest(
  v: unknown,
  p = "$"
): CreateChangeRequest {
  return decObject(v, p, (o) => ({
    kind: decodeChangeRequestKind(o.kind, `${p}.kind`),
    payload: decodeChangeRequestPayload(o.payload, `${p}.payload`),
    ...(o.note === undefined
      ? {}
      : { note: o.note === null ? null : decString(o.note, `${p}.note`) }),
  }))
}

export interface CreateChecklistItemRequest {
  title: string
  assigneeId?: string | null
}
export function decodeCreateChecklistItemRequest(
  v: unknown,
  p = "$"
): CreateChecklistItemRequest {
  return decObject(v, p, (o) => ({
    title: decString(o.title, `${p}.title`),
    ...(o.assigneeId === undefined
      ? {}
      : {
          assigneeId:
            o.assigneeId === null
              ? null
              : decString(o.assigneeId, `${p}.assigneeId`),
        }),
  }))
}

export interface CreateCommentRequest {
  body: string
  mentionedUserIds?: string[]
}
export function decodeCreateCommentRequest(
  v: unknown,
  p = "$"
): CreateCommentRequest {
  return decObject(v, p, (o) => ({
    body: decString(o.body, `${p}.body`),
    ...(o.mentionedUserIds === undefined
      ? {}
      : {
          mentionedUserIds: decArray(
            o.mentionedUserIds,
            `${p}.mentionedUserIds`,
            (x, xp) => decString(x, xp)
          ),
        }),
  }))
}

export interface CreateLabelRequest {
  name: string
  color: LabelColor
}
export function decodeCreateLabelRequest(
  v: unknown,
  p = "$"
): CreateLabelRequest {
  return decObject(v, p, (o) => ({
    name: decString(o.name, `${p}.name`),
    color: decodeLabelColor(o.color, `${p}.color`),
  }))
}

export interface CreateTaskRequest {
  title: string
  description?: string | null
  status?: TaskStatus
  priority?: TaskPriority
  startDate: string
  endDate: string
  dueDate?: string | null
  assigneeIds?: string[]
  labelIds?: string[]
  clientId?: string | null
  parentId?: string | null
}
export function decodeCreateTaskRequest(
  v: unknown,
  p = "$"
): CreateTaskRequest {
  return decObject(v, p, (o) => ({
    title: decString(o.title, `${p}.title`),
    ...(o.description === undefined
      ? {}
      : {
          description:
            o.description === null
              ? null
              : decString(o.description, `${p}.description`),
        }),
    ...(o.status === undefined
      ? {}
      : { status: decodeTaskStatus(o.status, `${p}.status`) }),
    ...(o.priority === undefined
      ? {}
      : { priority: decodeTaskPriority(o.priority, `${p}.priority`) }),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    ...(o.dueDate === undefined
      ? {}
      : {
          dueDate:
            o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
        }),
    ...(o.assigneeIds === undefined
      ? {}
      : {
          assigneeIds: decArray(o.assigneeIds, `${p}.assigneeIds`, (x, xp) =>
            decString(x, xp)
          ),
        }),
    ...(o.labelIds === undefined
      ? {}
      : {
          labelIds: decArray(o.labelIds, `${p}.labelIds`, (x, xp) =>
            decString(x, xp)
          ),
        }),
    ...(o.clientId === undefined
      ? {}
      : {
          clientId:
            o.clientId === null ? null : decString(o.clientId, `${p}.clientId`),
        }),
    ...(o.parentId === undefined
      ? {}
      : {
          parentId:
            o.parentId === null ? null : decString(o.parentId, `${p}.parentId`),
        }),
  }))
}

export interface CreateWorkspaceRequest {
  name: string
}
export function decodeCreateWorkspaceRequest(
  v: unknown,
  p = "$"
): CreateWorkspaceRequest {
  return decObject(v, p, (o) => ({ name: decString(o.name, `${p}.name`) }))
}

export interface FieldError {
  field: string
  message: string
}
export function decodeFieldError(v: unknown, p = "$"): FieldError {
  return decObject(v, p, (o) => ({
    field: decString(o.field, `${p}.field`),
    message: decString(o.message, `${p}.message`),
  }))
}

export interface Health {
  status: "ok"
}
export function decodeHealth(v: unknown, p = "$"): Health {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ok"] as const),
  }))
}

export interface InviteCodeResponse {
  inviteCode: string
}
export function decodeInviteCodeResponse(
  v: unknown,
  p = "$"
): InviteCodeResponse {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface JoinWorkspaceRequest {
  inviteCode: string
}
export function decodeJoinWorkspaceRequest(
  v: unknown,
  p = "$"
): JoinWorkspaceRequest {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface Label {
  id: string
  name: string
  color: LabelColor
}
export function decodeLabel(v: unknown, p = "$"): Label {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    color: decodeLabelColor(o.color, `${p}.color`),
  }))
}

export type LabelColor =
  | "gray"
  | "red"
  | "orange"
  | "yellow"
  | "green"
  | "teal"
  | "blue"
  | "purple"
  | "pink"
export function decodeLabelColor(v: unknown, p = "$"): LabelColor {
  return decEnum(v, p, [
    "gray",
    "red",
    "orange",
    "yellow",
    "green",
    "teal",
    "blue",
    "purple",
    "pink",
  ] as const)
}

export interface LabelIdsRequest {
  labelIds: string[]
}
export function decodeLabelIdsRequest(v: unknown, p = "$"): LabelIdsRequest {
  return decObject(v, p, (o) => ({
    labelIds: decArray(o.labelIds, `${p}.labelIds`, (x, xp) =>
      decString(x, xp)
    ),
  }))
}

export interface LabelList {
  labels: Label[]
}
export function decodeLabelList(v: unknown, p = "$"): LabelList {
  return decObject(v, p, (o) => ({
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
  }))
}

export interface LabelResponse {
  label: Label
}
export function decodeLabelResponse(v: unknown, p = "$"): LabelResponse {
  return decObject(v, p, (o) => ({ label: decodeLabel(o.label, `${p}.label`) }))
}

export interface Member {
  id: string
  name: string
  email: string
  image: string | null
  role: Role
  joinedAt: string
}
export function decodeMember(v: unknown, p = "$"): Member {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
    role: decodeRole(o.role, `${p}.role`),
    joinedAt: decString(o.joinedAt, `${p}.joinedAt`),
  }))
}

export interface MemberList {
  members: Member[]
}
export function decodeMemberList(v: unknown, p = "$"): MemberList {
  return decObject(v, p, (o) => ({
    members: decArray(o.members, `${p}.members`, (x, xp) =>
      decodeMember(x, xp)
    ),
  }))
}

export interface MeResponse {
  user: User
}
export function decodeMeResponse(v: unknown, p = "$"): MeResponse {
  return decObject(v, p, (o) => ({ user: decodeUser(o.user, `${p}.user`) }))
}

export interface Notification {
  id: string
  kind: NotificationKind
  task: NotificationTask | null
  taskTitle: string | null
  actor: PersonRef | null
  detail: string
  commentBody: string | null
  createdAt: string
  readAt: string | null
}
export function decodeNotification(v: unknown, p = "$"): Notification {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    kind: decodeNotificationKind(o.kind, `${p}.kind`),
    task: o.task === null ? null : decodeNotificationTask(o.task, `${p}.task`),
    taskTitle:
      o.taskTitle === null ? null : decString(o.taskTitle, `${p}.taskTitle`),
    actor: o.actor === null ? null : decodePersonRef(o.actor, `${p}.actor`),
    detail: decString(o.detail, `${p}.detail`),
    commentBody:
      o.commentBody === null
        ? null
        : decString(o.commentBody, `${p}.commentBody`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
    readAt: o.readAt === null ? null : decString(o.readAt, `${p}.readAt`),
  }))
}

export type NotificationKind =
  | "MENTION"
  | "ASSIGNED"
  | "STATUS"
  | "DUE"
  | "REQUEST"
  | "REVIEWED"
export function decodeNotificationKind(v: unknown, p = "$"): NotificationKind {
  return decEnum(v, p, [
    "MENTION",
    "ASSIGNED",
    "STATUS",
    "DUE",
    "REQUEST",
    "REVIEWED",
  ] as const)
}

export interface NotificationList {
  notifications: Notification[]
  unread: number
}
export function decodeNotificationList(v: unknown, p = "$"): NotificationList {
  return decObject(v, p, (o) => ({
    notifications: decArray(o.notifications, `${p}.notifications`, (x, xp) =>
      decodeNotification(x, xp)
    ),
    unread: decNumber(o.unread, `${p}.unread`, true),
  }))
}

export interface NotificationSetting {
  kind: NotificationKind
  enabled: boolean
}
export function decodeNotificationSetting(
  v: unknown,
  p = "$"
): NotificationSetting {
  return decObject(v, p, (o) => ({
    kind: decodeNotificationKind(o.kind, `${p}.kind`),
    enabled: decBoolean(o.enabled, `${p}.enabled`),
  }))
}

export interface NotificationSettings {
  settings: NotificationSetting[]
}
export function decodeNotificationSettings(
  v: unknown,
  p = "$"
): NotificationSettings {
  return decObject(v, p, (o) => ({
    settings: decArray(o.settings, `${p}.settings`, (x, xp) =>
      decodeNotificationSetting(x, xp)
    ),
  }))
}

export interface NotificationTask {
  id: string
  title: string
}
export function decodeNotificationTask(v: unknown, p = "$"): NotificationTask {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
  }))
}

export interface PersonRef {
  id: string
  name: string
  image: string | null
}
export function decodePersonRef(v: unknown, p = "$"): PersonRef {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
  }))
}

/** RFC 7807 problem details. */
export interface Problem {
  type: string
  title: string
  status: number
  detail?: string
  instance?: string
  requestId?: string
  errors?: FieldError[]
}
export function decodeProblem(v: unknown, p = "$"): Problem {
  return decObject(v, p, (o) => ({
    type: decString(o.type, `${p}.type`),
    title: decString(o.title, `${p}.title`),
    status: decNumber(o.status, `${p}.status`, true),
    ...(o.detail === undefined
      ? {}
      : { detail: decString(o.detail, `${p}.detail`) }),
    ...(o.instance === undefined
      ? {}
      : { instance: decString(o.instance, `${p}.instance`) }),
    ...(o.requestId === undefined
      ? {}
      : { requestId: decString(o.requestId, `${p}.requestId`) }),
    ...(o.errors === undefined
      ? {}
      : {
          errors: decArray(o.errors, `${p}.errors`, (x, xp) =>
            decodeFieldError(x, xp)
          ),
        }),
  }))
}

export interface Readiness {
  status: "ready" | "not_ready"
  checks: Record<string, string>
}
export function decodeReadiness(v: unknown, p = "$"): Readiness {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ready", "not_ready"] as const),
    checks: decRecord(o.checks, `${p}.checks`, (x, xp) => decString(x, xp)),
  }))
}

export interface ReviewChangeRequest {
  note?: string | null
}
export function decodeReviewChangeRequest(
  v: unknown,
  p = "$"
): ReviewChangeRequest {
  return decObject(v, p, (o) => ({
    ...(o.note === undefined
      ? {}
      : { note: o.note === null ? null : decString(o.note, `${p}.note`) }),
  }))
}

export type Role = "OWNER" | "MEMBER"
export function decodeRole(v: unknown, p = "$"): Role {
  return decEnum(v, p, ["OWNER", "MEMBER"] as const)
}

export interface StatusStage {
  status: TaskStatus
  enteredAt: string
  leftAt: string | null
}
export function decodeStatusStage(v: unknown, p = "$"): StatusStage {
  return decObject(v, p, (o) => ({
    status: decodeTaskStatus(o.status, `${p}.status`),
    enteredAt: decString(o.enteredAt, `${p}.enteredAt`),
    leftAt: o.leftAt === null ? null : decString(o.leftAt, `${p}.leftAt`),
  }))
}

export interface SwitchWorkspaceRequest {
  workspaceId: string
}
export function decodeSwitchWorkspaceRequest(
  v: unknown,
  p = "$"
): SwitchWorkspaceRequest {
  return decObject(v, p, (o) => ({
    workspaceId: decString(o.workspaceId, `${p}.workspaceId`),
  }))
}

export interface SystemInfo {
  service: string
  version: string
  startedAt: string
}
export function decodeSystemInfo(v: unknown, p = "$"): SystemInfo {
  return decObject(v, p, (o) => ({
    service: decString(o.service, `${p}.service`),
    version: decString(o.version, `${p}.version`),
    startedAt: decString(o.startedAt, `${p}.startedAt`),
  }))
}

export interface Task {
  id: string
  title: string
  description: string | null
  status: TaskStatus
  priority: TaskPriority
  startDate: string
  endDate: string
  dueDate: string | null
  assignees: PersonRef[]
  owners: PersonRef[]
  labels: Label[]
  createdBy: PersonRef
  createdAt: string
  updatedAt: string
  version: number
  viewer: TaskViewer
  client: ClientRef | null
  parent: TaskRef | null
  subtasks: TaskRef[]
  checklist: ChecklistItem[]
  comments: Comment[]
  attachments: Attachment[]
  requests: ChangeRequest[]
}
export function decodeTask(v: unknown, p = "$"): Task {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    description:
      o.description === null
        ? null
        : decString(o.description, `${p}.description`),
    status: decodeTaskStatus(o.status, `${p}.status`),
    priority: decodeTaskPriority(o.priority, `${p}.priority`),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    dueDate: o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
    assignees: decArray(o.assignees, `${p}.assignees`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    owners: decArray(o.owners, `${p}.owners`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
    createdBy: decodePersonRef(o.createdBy, `${p}.createdBy`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
    updatedAt: decString(o.updatedAt, `${p}.updatedAt`),
    version: decNumber(o.version, `${p}.version`, true),
    viewer: decodeTaskViewer(o.viewer, `${p}.viewer`),
    client: o.client === null ? null : decodeClientRef(o.client, `${p}.client`),
    parent: o.parent === null ? null : decodeTaskRef(o.parent, `${p}.parent`),
    subtasks: decArray(o.subtasks, `${p}.subtasks`, (x, xp) =>
      decodeTaskRef(x, xp)
    ),
    checklist: decArray(o.checklist, `${p}.checklist`, (x, xp) =>
      decodeChecklistItem(x, xp)
    ),
    comments: decArray(o.comments, `${p}.comments`, (x, xp) =>
      decodeComment(x, xp)
    ),
    attachments: decArray(o.attachments, `${p}.attachments`, (x, xp) =>
      decodeAttachment(x, xp)
    ),
    requests: decArray(o.requests, `${p}.requests`, (x, xp) =>
      decodeChangeRequest(x, xp)
    ),
  }))
}

export interface TaskCounts {
  pendingRequests: number
  subtasks: number
  subtasksDone: number
  checklist: number
  checklistDone: number
  comments: number
  attachments: number
}
export function decodeTaskCounts(v: unknown, p = "$"): TaskCounts {
  return decObject(v, p, (o) => ({
    pendingRequests: decNumber(o.pendingRequests, `${p}.pendingRequests`, true),
    subtasks: decNumber(o.subtasks, `${p}.subtasks`, true),
    subtasksDone: decNumber(o.subtasksDone, `${p}.subtasksDone`, true),
    checklist: decNumber(o.checklist, `${p}.checklist`, true),
    checklistDone: decNumber(o.checklistDone, `${p}.checklistDone`, true),
    comments: decNumber(o.comments, `${p}.comments`, true),
    attachments: decNumber(o.attachments, `${p}.attachments`, true),
  }))
}

export interface TaskEvent {
  id: string
  kind: TaskEventKind
  field: string | null
  from: string | null
  to: string | null
  subject: string | null
  actor: PersonRef | null
  createdAt: string
}
export function decodeTaskEvent(v: unknown, p = "$"): TaskEvent {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    kind: decodeTaskEventKind(o.kind, `${p}.kind`),
    field: o.field === null ? null : decString(o.field, `${p}.field`),
    from: o.from === null ? null : decString(o.from, `${p}.from`),
    to: o.to === null ? null : decString(o.to, `${p}.to`),
    subject: o.subject === null ? null : decString(o.subject, `${p}.subject`),
    actor: o.actor === null ? null : decodePersonRef(o.actor, `${p}.actor`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
  }))
}

export type TaskEventKind =
  | "CREATED"
  | "STATUS"
  | "UPDATED"
  | "ASSIGNEE_ADDED"
  | "ASSIGNEE_REMOVED"
  | "LABEL_ADDED"
  | "LABEL_REMOVED"
  | "OWNER_ADDED"
  | "OWNER_REMOVED"
  | "CHECKLIST_ADDED"
  | "CHECKLIST_CHECKED"
  | "CHECKLIST_UNCHECKED"
  | "CHECKLIST_RENAMED"
  | "CHECKLIST_ASSIGNED"
  | "CHECKLIST_UNASSIGNED"
  | "CHECKLIST_REMOVED"
  | "COMMENTED"
  | "ATTACHMENT_ADDED"
  | "ATTACHMENT_REMOVED"
  | "SUBTASK_ADDED"
  | "REQUEST_CREATED"
  | "REQUEST_APPROVED"
  | "REQUEST_REJECTED"
  | "REQUEST_CANCELED"
export function decodeTaskEventKind(v: unknown, p = "$"): TaskEventKind {
  return decEnum(v, p, [
    "CREATED",
    "STATUS",
    "UPDATED",
    "ASSIGNEE_ADDED",
    "ASSIGNEE_REMOVED",
    "LABEL_ADDED",
    "LABEL_REMOVED",
    "OWNER_ADDED",
    "OWNER_REMOVED",
    "CHECKLIST_ADDED",
    "CHECKLIST_CHECKED",
    "CHECKLIST_UNCHECKED",
    "CHECKLIST_RENAMED",
    "CHECKLIST_ASSIGNED",
    "CHECKLIST_UNASSIGNED",
    "CHECKLIST_REMOVED",
    "COMMENTED",
    "ATTACHMENT_ADDED",
    "ATTACHMENT_REMOVED",
    "SUBTASK_ADDED",
    "REQUEST_CREATED",
    "REQUEST_APPROVED",
    "REQUEST_REJECTED",
    "REQUEST_CANCELED",
  ] as const)
}

export interface TaskHistory {
  events: TaskEvent[]
  stages: StatusStage[]
}
export function decodeTaskHistory(v: unknown, p = "$"): TaskHistory {
  return decObject(v, p, (o) => ({
    events: decArray(o.events, `${p}.events`, (x, xp) =>
      decodeTaskEvent(x, xp)
    ),
    stages: decArray(o.stages, `${p}.stages`, (x, xp) =>
      decodeStatusStage(x, xp)
    ),
  }))
}

export interface TaskList {
  tasks: TaskSummary[]
}
export function decodeTaskList(v: unknown, p = "$"): TaskList {
  return decObject(v, p, (o) => ({
    tasks: decArray(o.tasks, `${p}.tasks`, (x, xp) => decodeTaskSummary(x, xp)),
  }))
}

export type TaskPriority = "URGENT" | "HIGH" | "MEDIUM" | "LOW" | "NONE"
export function decodeTaskPriority(v: unknown, p = "$"): TaskPriority {
  return decEnum(v, p, ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] as const)
}

export interface TaskRef {
  id: string
  title: string
  status: TaskStatus
}
export function decodeTaskRef(v: unknown, p = "$"): TaskRef {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    status: decodeTaskStatus(o.status, `${p}.status`),
  }))
}

export interface TaskResponse {
  task: Task
}
export function decodeTaskResponse(v: unknown, p = "$"): TaskResponse {
  return decObject(v, p, (o) => ({ task: decodeTask(o.task, `${p}.task`) }))
}

export type TaskStatus =
  | "BACKLOG"
  | "TODO"
  | "IN_PROGRESS"
  | "TESTING"
  | "DONE"
  | "CANCELED"
export function decodeTaskStatus(v: unknown, p = "$"): TaskStatus {
  return decEnum(v, p, [
    "BACKLOG",
    "TODO",
    "IN_PROGRESS",
    "TESTING",
    "DONE",
    "CANCELED",
  ] as const)
}

export interface TaskSummary {
  id: string
  title: string
  status: TaskStatus
  priority: TaskPriority
  startDate: string
  endDate: string
  dueDate: string | null
  assignees: PersonRef[]
  labels: Label[]
  createdBy: PersonRef
  version: number
  updatedAt: string
  client: ClientRef | null
  parent: TaskRef | null
  counts: TaskCounts
}
export function decodeTaskSummary(v: unknown, p = "$"): TaskSummary {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    status: decodeTaskStatus(o.status, `${p}.status`),
    priority: decodeTaskPriority(o.priority, `${p}.priority`),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    dueDate: o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
    assignees: decArray(o.assignees, `${p}.assignees`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
    createdBy: decodePersonRef(o.createdBy, `${p}.createdBy`),
    version: decNumber(o.version, `${p}.version`, true),
    updatedAt: decString(o.updatedAt, `${p}.updatedAt`),
    client: o.client === null ? null : decodeClientRef(o.client, `${p}.client`),
    parent: o.parent === null ? null : decodeTaskRef(o.parent, `${p}.parent`),
    counts: decodeTaskCounts(o.counts, `${p}.counts`),
  }))
}

/** The caller's permissions on this task (E5-S1). */
export interface TaskViewer {
  canManage: boolean
  canManageOwners: boolean
  isAssignee: boolean
  canRequest: boolean
}
export function decodeTaskViewer(v: unknown, p = "$"): TaskViewer {
  return decObject(v, p, (o) => ({
    canManage: decBoolean(o.canManage, `${p}.canManage`),
    canManageOwners: decBoolean(o.canManageOwners, `${p}.canManageOwners`),
    isAssignee: decBoolean(o.isAssignee, `${p}.isAssignee`),
    canRequest: decBoolean(o.canRequest, `${p}.canRequest`),
  }))
}

export interface UpdateChecklistItemRequest {
  title?: string
  done?: boolean
  assigneeId?: string | null
}
export function decodeUpdateChecklistItemRequest(
  v: unknown,
  p = "$"
): UpdateChecklistItemRequest {
  return decObject(v, p, (o) => ({
    ...(o.title === undefined
      ? {}
      : { title: decString(o.title, `${p}.title`) }),
    ...(o.done === undefined ? {} : { done: decBoolean(o.done, `${p}.done`) }),
    ...(o.assigneeId === undefined
      ? {}
      : {
          assigneeId:
            o.assigneeId === null
              ? null
              : decString(o.assigneeId, `${p}.assigneeId`),
        }),
  }))
}

/** Only the fields present are changed. */
export interface UpdateTaskRequest {
  title?: string
  description?: string | null
  status?: TaskStatus
  priority?: TaskPriority
  startDate?: string
  endDate?: string
  dueDate?: string | null
  clientId?: string | null
}
export function decodeUpdateTaskRequest(
  v: unknown,
  p = "$"
): UpdateTaskRequest {
  return decObject(v, p, (o) => ({
    ...(o.title === undefined
      ? {}
      : { title: decString(o.title, `${p}.title`) }),
    ...(o.description === undefined
      ? {}
      : {
          description:
            o.description === null
              ? null
              : decString(o.description, `${p}.description`),
        }),
    ...(o.status === undefined
      ? {}
      : { status: decodeTaskStatus(o.status, `${p}.status`) }),
    ...(o.priority === undefined
      ? {}
      : { priority: decodeTaskPriority(o.priority, `${p}.priority`) }),
    ...(o.startDate === undefined
      ? {}
      : { startDate: decString(o.startDate, `${p}.startDate`) }),
    ...(o.endDate === undefined
      ? {}
      : { endDate: decString(o.endDate, `${p}.endDate`) }),
    ...(o.dueDate === undefined
      ? {}
      : {
          dueDate:
            o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
        }),
    ...(o.clientId === undefined
      ? {}
      : {
          clientId:
            o.clientId === null ? null : decString(o.clientId, `${p}.clientId`),
        }),
  }))
}

export interface UploadTarget {
  method: "PUT"
  url: string
  headers: Record<string, string>
}
export function decodeUploadTarget(v: unknown, p = "$"): UploadTarget {
  return decObject(v, p, (o) => ({
    method: decEnum(o.method, `${p}.method`, ["PUT"] as const),
    url: decString(o.url, `${p}.url`),
    headers: decRecord(o.headers, `${p}.headers`, (x, xp) => decString(x, xp)),
  }))
}

export interface User {
  id: string
  name: string
  email: string
  image: string | null
}
export function decodeUser(v: unknown, p = "$"): User {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
  }))
}

export interface UserIdsRequest {
  userIds: string[]
}
export function decodeUserIdsRequest(v: unknown, p = "$"): UserIdsRequest {
  return decObject(v, p, (o) => ({
    userIds: decArray(o.userIds, `${p}.userIds`, (x, xp) => decString(x, xp)),
  }))
}

export interface Workspace {
  id: string
  name: string
  role: Role
}
export function decodeWorkspace(v: unknown, p = "$"): Workspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
  }))
}

export interface WorkspaceList {
  workspaces: Workspace[]
  active: ActiveWorkspace | null
}
export function decodeWorkspaceList(v: unknown, p = "$"): WorkspaceList {
  return decObject(v, p, (o) => ({
    workspaces: decArray(o.workspaces, `${p}.workspaces`, (x, xp) =>
      decodeWorkspace(x, xp)
    ),
    active:
      o.active === null ? null : decodeActiveWorkspace(o.active, `${p}.active`),
  }))
}

export interface WorkspaceResponse {
  workspace: Workspace
}
export function decodeWorkspaceResponse(
  v: unknown,
  p = "$"
): WorkspaceResponse {
  return decObject(v, p, (o) => ({
    workspace: decodeWorkspace(o.workspace, `${p}.workspace`),
  }))
}
