/* GENERATED by scripts/gen-api.mjs from api/openapi.yaml - do not edit. */
/* Regenerate with `pnpm gen:api` (ADR-0018). */

/** A response did not match api/openapi.yaml. `path` is a JSON path like $.user.id */
export class DecodeError extends Error {
  constructor(
    readonly path: string,
    readonly expected: string
  ) {
    super(`Unexpected API response at ${path}: expected ${expected}`)
    this.name = "DecodeError"
  }
}

type Obj = Record<string, unknown>

function fail(path: string, expected: string): never {
  throw new DecodeError(path, expected)
}

function decObject<T>(v: unknown, p: string, f: (o: Obj) => T): T {
  if (typeof v !== "object" || v === null || Array.isArray(v)) fail(p, "object")
  return f(v as Obj)
}
function decRecord<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): Record<string, T> {
  return decObject(v, p, (o) =>
    Object.fromEntries(
      Object.entries(o).map(([k, x]) => [k, f(x, `${p}.${k}`)])
    )
  )
}
function decArray<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): T[] {
  if (!Array.isArray(v)) fail(p, "array")
  return v.map((x, i) => f(x, `${p}[${i}]`))
}
function decString(v: unknown, p: string): string {
  return typeof v === "string" ? v : fail(p, "string")
}
function decNumber(v: unknown, p: string, integer: boolean): number {
  if (typeof v !== "number" || Number.isNaN(v)) fail(p, "number")
  if (integer && !Number.isInteger(v)) fail(p, "integer")
  return v
}
function decEnum<const T extends readonly string[]>(
  v: unknown,
  p: string,
  values: T
): T[number] {
  return typeof v === "string" && values.includes(v)
    ? (v as T[number])
    : fail(p, values.join(" | "))
}

export interface ActiveWorkspace {
  id: string
  name: string
  role: Role
  inviteCode: string
}
export function decodeActiveWorkspace(v: unknown, p = "$"): ActiveWorkspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface CreateWorkspaceRequest {
  name: string
}
export function decodeCreateWorkspaceRequest(
  v: unknown,
  p = "$"
): CreateWorkspaceRequest {
  return decObject(v, p, (o) => ({ name: decString(o.name, `${p}.name`) }))
}

export interface FieldError {
  field: string
  message: string
}
export function decodeFieldError(v: unknown, p = "$"): FieldError {
  return decObject(v, p, (o) => ({
    field: decString(o.field, `${p}.field`),
    message: decString(o.message, `${p}.message`),
  }))
}

export interface Health {
  status: "ok"
}
export function decodeHealth(v: unknown, p = "$"): Health {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ok"] as const),
  }))
}

export interface InviteCodeResponse {
  inviteCode: string
}
export function decodeInviteCodeResponse(
  v: unknown,
  p = "$"
): InviteCodeResponse {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface JoinWorkspaceRequest {
  inviteCode: string
}
export function decodeJoinWorkspaceRequest(
  v: unknown,
  p = "$"
): JoinWorkspaceRequest {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface Member {
  id: string
  name: string
  email: string
  image: string | null
  role: Role
  joinedAt: string
}
export function decodeMember(v: unknown, p = "$"): Member {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
    role: decodeRole(o.role, `${p}.role`),
    joinedAt: decString(o.joinedAt, `${p}.joinedAt`),
  }))
}

export interface MemberList {
  members: Member[]
}
export function decodeMemberList(v: unknown, p = "$"): MemberList {
  return decObject(v, p, (o) => ({
    members: decArray(o.members, `${p}.members`, (x, xp) =>
      decodeMember(x, xp)
    ),
  }))
}

export interface MeResponse {
  user: User
}
export function decodeMeResponse(v: unknown, p = "$"): MeResponse {
  return decObject(v, p, (o) => ({ user: decodeUser(o.user, `${p}.user`) }))
}

/** RFC 7807 problem details. */
export interface Problem {
  type: string
  title: string
  status: number
  detail?: string
  instance?: string
  requestId?: string
  errors?: FieldError[]
}
export function decodeProblem(v: unknown, p = "$"): Problem {
  return decObject(v, p, (o) => ({
    type: decString(o.type, `${p}.type`),
    title: decString(o.title, `${p}.title`),
    status: decNumber(o.status, `${p}.status`, true),
    ...(o.detail === undefined
      ? {}
      : { detail: decString(o.detail, `${p}.detail`) }),
    ...(o.instance === undefined
      ? {}
      : { instance: decString(o.instance, `${p}.instance`) }),
    ...(o.requestId === undefined
      ? {}
      : { requestId: decString(o.requestId, `${p}.requestId`) }),
    ...(o.errors === undefined
      ? {}
      : {
          errors: decArray(o.errors, `${p}.errors`, (x, xp) =>
            decodeFieldError(x, xp)
          ),
        }),
  }))
}

export interface Readiness {
  status: "ready" | "not_ready"
  checks: Record<string, string>
}
export function decodeReadiness(v: unknown, p = "$"): Readiness {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ready", "not_ready"] as const),
    checks: decRecord(o.checks, `${p}.checks`, (x, xp) => decString(x, xp)),
  }))
}

export type Role = "OWNER" | "MEMBER"
export function decodeRole(v: unknown, p = "$"): Role {
  return decEnum(v, p, ["OWNER", "MEMBER"] as const)
}

export interface SwitchWorkspaceRequest {
  workspaceId: string
}
export function decodeSwitchWorkspaceRequest(
  v: unknown,
  p = "$"
): SwitchWorkspaceRequest {
  return decObject(v, p, (o) => ({
    workspaceId: decString(o.workspaceId, `${p}.workspaceId`),
  }))
}

export interface SystemInfo {
  service: string
  version: string
  startedAt: string
}
export function decodeSystemInfo(v: unknown, p = "$"): SystemInfo {
  return decObject(v, p, (o) => ({
    service: decString(o.service, `${p}.service`),
    version: decString(o.version, `${p}.version`),
    startedAt: decString(o.startedAt, `${p}.startedAt`),
  }))
}

export interface User {
  id: string
  name: string
  email: string
  image: string | null
}
export function decodeUser(v: unknown, p = "$"): User {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
  }))
}

export interface Workspace {
  id: string
  name: string
  role: Role
}
export function decodeWorkspace(v: unknown, p = "$"): Workspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
  }))
}

export interface WorkspaceList {
  workspaces: Workspace[]
  active: ActiveWorkspace | null
}
export function decodeWorkspaceList(v: unknown, p = "$"): WorkspaceList {
  return decObject(v, p, (o) => ({
    workspaces: decArray(o.workspaces, `${p}.workspaces`, (x, xp) =>
      decodeWorkspace(x, xp)
    ),
    active:
      o.active === null ? null : decodeActiveWorkspace(o.active, `${p}.active`),
  }))
}

export interface WorkspaceResponse {
  workspace: Workspace
}
export function decodeWorkspaceResponse(
  v: unknown,
  p = "$"
): WorkspaceResponse {
  return decObject(v, p, (o) => ({
    workspace: decodeWorkspace(o.workspace, `${p}.workspace`),
  }))
}
