/* GENERATED by scripts/gen-api.mjs from api/openapi.yaml - do not edit. */
/* Regenerate with `pnpm gen:api` (ADR-0018). */

/** A response did not match api/openapi.yaml. `path` is a JSON path like $.user.id */
export class DecodeError extends Error {
  constructor(
    readonly path: string,
    readonly expected: string
  ) {
    super(`Unexpected API response at ${path}: expected ${expected}`)
    this.name = "DecodeError"
  }
}

type Obj = Record<string, unknown>

function fail(path: string, expected: string): never {
  throw new DecodeError(path, expected)
}

function decObject<T>(v: unknown, p: string, f: (o: Obj) => T): T {
  if (typeof v !== "object" || v === null || Array.isArray(v)) fail(p, "object")
  return f(v as Obj)
}
function decRecord<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): Record<string, T> {
  return decObject(v, p, (o) =>
    Object.fromEntries(
      Object.entries(o).map(([k, x]) => [k, f(x, `${p}.${k}`)])
    )
  )
}
function decArray<T>(
  v: unknown,
  p: string,
  f: (x: unknown, p: string) => T
): T[] {
  if (!Array.isArray(v)) fail(p, "array")
  return v.map((x, i) => f(x, `${p}[${i}]`))
}
function decString(v: unknown, p: string): string {
  return typeof v === "string" ? v : fail(p, "string")
}
function decNumber(v: unknown, p: string, integer: boolean): number {
  if (typeof v !== "number" || Number.isNaN(v)) fail(p, "number")
  if (integer && !Number.isInteger(v)) fail(p, "integer")
  return v
}
function decBoolean(v: unknown, p: string): boolean {
  return typeof v === "boolean" ? v : fail(p, "boolean")
}
function decEnum<const T extends readonly string[]>(
  v: unknown,
  p: string,
  values: T
): T[number] {
  return typeof v === "string" && values.includes(v)
    ? (v as T[number])
    : fail(p, values.join(" | "))
}

export interface ActiveWorkspace {
  id: string
  name: string
  role: Role
  inviteCode: string
}
export function decodeActiveWorkspace(v: unknown, p = "$"): ActiveWorkspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface CreateLabelRequest {
  name: string
  color: LabelColor
}
export function decodeCreateLabelRequest(
  v: unknown,
  p = "$"
): CreateLabelRequest {
  return decObject(v, p, (o) => ({
    name: decString(o.name, `${p}.name`),
    color: decodeLabelColor(o.color, `${p}.color`),
  }))
}

export interface CreateTaskRequest {
  title: string
  description?: string | null
  status?: TaskStatus
  priority?: TaskPriority
  startDate: string
  endDate: string
  dueDate?: string | null
  assigneeIds?: string[]
  labelIds?: string[]
}
export function decodeCreateTaskRequest(
  v: unknown,
  p = "$"
): CreateTaskRequest {
  return decObject(v, p, (o) => ({
    title: decString(o.title, `${p}.title`),
    ...(o.description === undefined
      ? {}
      : {
          description:
            o.description === null
              ? null
              : decString(o.description, `${p}.description`),
        }),
    ...(o.status === undefined
      ? {}
      : { status: decodeTaskStatus(o.status, `${p}.status`) }),
    ...(o.priority === undefined
      ? {}
      : { priority: decodeTaskPriority(o.priority, `${p}.priority`) }),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    ...(o.dueDate === undefined
      ? {}
      : {
          dueDate:
            o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
        }),
    ...(o.assigneeIds === undefined
      ? {}
      : {
          assigneeIds: decArray(o.assigneeIds, `${p}.assigneeIds`, (x, xp) =>
            decString(x, xp)
          ),
        }),
    ...(o.labelIds === undefined
      ? {}
      : {
          labelIds: decArray(o.labelIds, `${p}.labelIds`, (x, xp) =>
            decString(x, xp)
          ),
        }),
  }))
}

export interface CreateWorkspaceRequest {
  name: string
}
export function decodeCreateWorkspaceRequest(
  v: unknown,
  p = "$"
): CreateWorkspaceRequest {
  return decObject(v, p, (o) => ({ name: decString(o.name, `${p}.name`) }))
}

export interface FieldError {
  field: string
  message: string
}
export function decodeFieldError(v: unknown, p = "$"): FieldError {
  return decObject(v, p, (o) => ({
    field: decString(o.field, `${p}.field`),
    message: decString(o.message, `${p}.message`),
  }))
}

export interface Health {
  status: "ok"
}
export function decodeHealth(v: unknown, p = "$"): Health {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ok"] as const),
  }))
}

export interface InviteCodeResponse {
  inviteCode: string
}
export function decodeInviteCodeResponse(
  v: unknown,
  p = "$"
): InviteCodeResponse {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface JoinWorkspaceRequest {
  inviteCode: string
}
export function decodeJoinWorkspaceRequest(
  v: unknown,
  p = "$"
): JoinWorkspaceRequest {
  return decObject(v, p, (o) => ({
    inviteCode: decString(o.inviteCode, `${p}.inviteCode`),
  }))
}

export interface Label {
  id: string
  name: string
  color: LabelColor
}
export function decodeLabel(v: unknown, p = "$"): Label {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    color: decodeLabelColor(o.color, `${p}.color`),
  }))
}

export type LabelColor =
  | "gray"
  | "red"
  | "orange"
  | "yellow"
  | "green"
  | "teal"
  | "blue"
  | "purple"
  | "pink"
export function decodeLabelColor(v: unknown, p = "$"): LabelColor {
  return decEnum(v, p, [
    "gray",
    "red",
    "orange",
    "yellow",
    "green",
    "teal",
    "blue",
    "purple",
    "pink",
  ] as const)
}

export interface LabelIdsRequest {
  labelIds: string[]
}
export function decodeLabelIdsRequest(v: unknown, p = "$"): LabelIdsRequest {
  return decObject(v, p, (o) => ({
    labelIds: decArray(o.labelIds, `${p}.labelIds`, (x, xp) =>
      decString(x, xp)
    ),
  }))
}

export interface LabelList {
  labels: Label[]
}
export function decodeLabelList(v: unknown, p = "$"): LabelList {
  return decObject(v, p, (o) => ({
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
  }))
}

export interface LabelResponse {
  label: Label
}
export function decodeLabelResponse(v: unknown, p = "$"): LabelResponse {
  return decObject(v, p, (o) => ({ label: decodeLabel(o.label, `${p}.label`) }))
}

export interface Member {
  id: string
  name: string
  email: string
  image: string | null
  role: Role
  joinedAt: string
}
export function decodeMember(v: unknown, p = "$"): Member {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
    role: decodeRole(o.role, `${p}.role`),
    joinedAt: decString(o.joinedAt, `${p}.joinedAt`),
  }))
}

export interface MemberList {
  members: Member[]
}
export function decodeMemberList(v: unknown, p = "$"): MemberList {
  return decObject(v, p, (o) => ({
    members: decArray(o.members, `${p}.members`, (x, xp) =>
      decodeMember(x, xp)
    ),
  }))
}

export interface MeResponse {
  user: User
}
export function decodeMeResponse(v: unknown, p = "$"): MeResponse {
  return decObject(v, p, (o) => ({ user: decodeUser(o.user, `${p}.user`) }))
}

export interface PersonRef {
  id: string
  name: string
  image: string | null
}
export function decodePersonRef(v: unknown, p = "$"): PersonRef {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
  }))
}

/** RFC 7807 problem details. */
export interface Problem {
  type: string
  title: string
  status: number
  detail?: string
  instance?: string
  requestId?: string
  errors?: FieldError[]
}
export function decodeProblem(v: unknown, p = "$"): Problem {
  return decObject(v, p, (o) => ({
    type: decString(o.type, `${p}.type`),
    title: decString(o.title, `${p}.title`),
    status: decNumber(o.status, `${p}.status`, true),
    ...(o.detail === undefined
      ? {}
      : { detail: decString(o.detail, `${p}.detail`) }),
    ...(o.instance === undefined
      ? {}
      : { instance: decString(o.instance, `${p}.instance`) }),
    ...(o.requestId === undefined
      ? {}
      : { requestId: decString(o.requestId, `${p}.requestId`) }),
    ...(o.errors === undefined
      ? {}
      : {
          errors: decArray(o.errors, `${p}.errors`, (x, xp) =>
            decodeFieldError(x, xp)
          ),
        }),
  }))
}

export interface Readiness {
  status: "ready" | "not_ready"
  checks: Record<string, string>
}
export function decodeReadiness(v: unknown, p = "$"): Readiness {
  return decObject(v, p, (o) => ({
    status: decEnum(o.status, `${p}.status`, ["ready", "not_ready"] as const),
    checks: decRecord(o.checks, `${p}.checks`, (x, xp) => decString(x, xp)),
  }))
}

export type Role = "OWNER" | "MEMBER"
export function decodeRole(v: unknown, p = "$"): Role {
  return decEnum(v, p, ["OWNER", "MEMBER"] as const)
}

export interface SwitchWorkspaceRequest {
  workspaceId: string
}
export function decodeSwitchWorkspaceRequest(
  v: unknown,
  p = "$"
): SwitchWorkspaceRequest {
  return decObject(v, p, (o) => ({
    workspaceId: decString(o.workspaceId, `${p}.workspaceId`),
  }))
}

export interface SystemInfo {
  service: string
  version: string
  startedAt: string
}
export function decodeSystemInfo(v: unknown, p = "$"): SystemInfo {
  return decObject(v, p, (o) => ({
    service: decString(o.service, `${p}.service`),
    version: decString(o.version, `${p}.version`),
    startedAt: decString(o.startedAt, `${p}.startedAt`),
  }))
}

export interface Task {
  id: string
  title: string
  description: string | null
  status: TaskStatus
  priority: TaskPriority
  startDate: string
  endDate: string
  dueDate: string | null
  assignees: PersonRef[]
  owners: PersonRef[]
  labels: Label[]
  createdBy: PersonRef
  createdAt: string
  updatedAt: string
  version: number
  viewer: TaskViewer
}
export function decodeTask(v: unknown, p = "$"): Task {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    description:
      o.description === null
        ? null
        : decString(o.description, `${p}.description`),
    status: decodeTaskStatus(o.status, `${p}.status`),
    priority: decodeTaskPriority(o.priority, `${p}.priority`),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    dueDate: o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
    assignees: decArray(o.assignees, `${p}.assignees`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    owners: decArray(o.owners, `${p}.owners`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
    createdBy: decodePersonRef(o.createdBy, `${p}.createdBy`),
    createdAt: decString(o.createdAt, `${p}.createdAt`),
    updatedAt: decString(o.updatedAt, `${p}.updatedAt`),
    version: decNumber(o.version, `${p}.version`, true),
    viewer: decodeTaskViewer(o.viewer, `${p}.viewer`),
  }))
}

export interface TaskList {
  tasks: TaskSummary[]
}
export function decodeTaskList(v: unknown, p = "$"): TaskList {
  return decObject(v, p, (o) => ({
    tasks: decArray(o.tasks, `${p}.tasks`, (x, xp) => decodeTaskSummary(x, xp)),
  }))
}

export type TaskPriority = "URGENT" | "HIGH" | "MEDIUM" | "LOW" | "NONE"
export function decodeTaskPriority(v: unknown, p = "$"): TaskPriority {
  return decEnum(v, p, ["URGENT", "HIGH", "MEDIUM", "LOW", "NONE"] as const)
}

export interface TaskResponse {
  task: Task
}
export function decodeTaskResponse(v: unknown, p = "$"): TaskResponse {
  return decObject(v, p, (o) => ({ task: decodeTask(o.task, `${p}.task`) }))
}

export type TaskStatus =
  | "BACKLOG"
  | "TODO"
  | "IN_PROGRESS"
  | "TESTING"
  | "DONE"
  | "CANCELED"
export function decodeTaskStatus(v: unknown, p = "$"): TaskStatus {
  return decEnum(v, p, [
    "BACKLOG",
    "TODO",
    "IN_PROGRESS",
    "TESTING",
    "DONE",
    "CANCELED",
  ] as const)
}

export interface TaskSummary {
  id: string
  title: string
  status: TaskStatus
  priority: TaskPriority
  startDate: string
  endDate: string
  dueDate: string | null
  assignees: PersonRef[]
  labels: Label[]
  createdBy: PersonRef
  version: number
  updatedAt: string
}
export function decodeTaskSummary(v: unknown, p = "$"): TaskSummary {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    title: decString(o.title, `${p}.title`),
    status: decodeTaskStatus(o.status, `${p}.status`),
    priority: decodeTaskPriority(o.priority, `${p}.priority`),
    startDate: decString(o.startDate, `${p}.startDate`),
    endDate: decString(o.endDate, `${p}.endDate`),
    dueDate: o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
    assignees: decArray(o.assignees, `${p}.assignees`, (x, xp) =>
      decodePersonRef(x, xp)
    ),
    labels: decArray(o.labels, `${p}.labels`, (x, xp) => decodeLabel(x, xp)),
    createdBy: decodePersonRef(o.createdBy, `${p}.createdBy`),
    version: decNumber(o.version, `${p}.version`, true),
    updatedAt: decString(o.updatedAt, `${p}.updatedAt`),
  }))
}

/** The caller's permissions on this task (E5-S1). */
export interface TaskViewer {
  canManage: boolean
  canManageOwners: boolean
  isAssignee: boolean
}
export function decodeTaskViewer(v: unknown, p = "$"): TaskViewer {
  return decObject(v, p, (o) => ({
    canManage: decBoolean(o.canManage, `${p}.canManage`),
    canManageOwners: decBoolean(o.canManageOwners, `${p}.canManageOwners`),
    isAssignee: decBoolean(o.isAssignee, `${p}.isAssignee`),
  }))
}

/** Only the fields present are changed. */
export interface UpdateTaskRequest {
  title?: string
  description?: string | null
  status?: TaskStatus
  priority?: TaskPriority
  startDate?: string
  endDate?: string
  dueDate?: string | null
}
export function decodeUpdateTaskRequest(
  v: unknown,
  p = "$"
): UpdateTaskRequest {
  return decObject(v, p, (o) => ({
    ...(o.title === undefined
      ? {}
      : { title: decString(o.title, `${p}.title`) }),
    ...(o.description === undefined
      ? {}
      : {
          description:
            o.description === null
              ? null
              : decString(o.description, `${p}.description`),
        }),
    ...(o.status === undefined
      ? {}
      : { status: decodeTaskStatus(o.status, `${p}.status`) }),
    ...(o.priority === undefined
      ? {}
      : { priority: decodeTaskPriority(o.priority, `${p}.priority`) }),
    ...(o.startDate === undefined
      ? {}
      : { startDate: decString(o.startDate, `${p}.startDate`) }),
    ...(o.endDate === undefined
      ? {}
      : { endDate: decString(o.endDate, `${p}.endDate`) }),
    ...(o.dueDate === undefined
      ? {}
      : {
          dueDate:
            o.dueDate === null ? null : decString(o.dueDate, `${p}.dueDate`),
        }),
  }))
}

export interface User {
  id: string
  name: string
  email: string
  image: string | null
}
export function decodeUser(v: unknown, p = "$"): User {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    email: decString(o.email, `${p}.email`),
    image: o.image === null ? null : decString(o.image, `${p}.image`),
  }))
}

export interface UserIdsRequest {
  userIds: string[]
}
export function decodeUserIdsRequest(v: unknown, p = "$"): UserIdsRequest {
  return decObject(v, p, (o) => ({
    userIds: decArray(o.userIds, `${p}.userIds`, (x, xp) => decString(x, xp)),
  }))
}

export interface Workspace {
  id: string
  name: string
  role: Role
}
export function decodeWorkspace(v: unknown, p = "$"): Workspace {
  return decObject(v, p, (o) => ({
    id: decString(o.id, `${p}.id`),
    name: decString(o.name, `${p}.name`),
    role: decodeRole(o.role, `${p}.role`),
  }))
}

export interface WorkspaceList {
  workspaces: Workspace[]
  active: ActiveWorkspace | null
}
export function decodeWorkspaceList(v: unknown, p = "$"): WorkspaceList {
  return decObject(v, p, (o) => ({
    workspaces: decArray(o.workspaces, `${p}.workspaces`, (x, xp) =>
      decodeWorkspace(x, xp)
    ),
    active:
      o.active === null ? null : decodeActiveWorkspace(o.active, `${p}.active`),
  }))
}

export interface WorkspaceResponse {
  workspace: Workspace
}
export function decodeWorkspaceResponse(
  v: unknown,
  p = "$"
): WorkspaceResponse {
  return decObject(v, p, (o) => ({
    workspace: decodeWorkspace(o.workspace, `${p}.workspace`),
  }))
}
